# -*- coding: utf-8 -*-
"""VB-196

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8uUSRx3HXfXp6of4FLxFydhBa8vDLKG
"""

import argparse
import json
import torch
import torchaudio
from silero_vad import load_silero_vad, get_speech_timestamps

SAMPLING_RATE = 16000

torch.set_num_threads(1)


# ---- Load & Split ----

def load_stereo(filepath):
    """Load stereo wav, return left, right as 1D tensors at 16kHz."""
    wav, sr = torchaudio.load(filepath)

    # resample if needed
    if sr != SAMPLING_RATE:
        wav = torchaudio.transforms.Resample(sr, SAMPLING_RATE)(wav)

    if wav.shape[0] < 2:
        raise ValueError(f"Expected stereo (2 channels), got {wav.shape[0]} channel(s)")

    left = wav[0]
    right = wav[1]
    duration = len(left) / SAMPLING_RATE

    print(f"Loaded: {filepath}")
    print(f"  Duration: {duration:.2f}s | Sample Rate: {SAMPLING_RATE} Hz")

    return left, right, duration


# ---- VAD ----

def get_speech_segments(model, audio_tensor):
    """Run Silero VAD, return list of dicts with start/end in seconds."""
    timestamps = get_speech_timestamps(
        audio_tensor,
        model,
        sampling_rate=SAMPLING_RATE,
        return_seconds=True
    )
    # timestamps = [{'start': 0.5, 'end': 3.2}, ...]
    return timestamps


# ---- Overlap Detection ----

def segments_overlap(seg_a, seg_b):
    """Check if two segments overlap in time."""
    return seg_a['start'] < seg_b['end'] and seg_b['start'] < seg_a['end']


def classify_segments(processed_segs, reference_segs):
    """
    For each processed segment, check if any reference segment overlaps.
      - ISOLATED = no overlap  -> usable
      - OVERLAP  = has overlap -> rejected
    """
    results = []

    for p in processed_segs:
        has_overlap = any(segments_overlap(p, r) for r in reference_segs)

        results.append({
            'start': round(p['start'], 3),
            'end': round(p['end'], 3),
            'duration': round(p['end'] - p['start'], 3),
            'status': 'OVERLAP' if has_overlap else 'ISOLATED'
        })

    return results


# ---- Analysis for one channel ----

def analyze_channel(model, left, right, total_duration, processed_ch='L'):
    """Run full analysis for one processed channel."""

    if processed_ch == 'L':
        proc_audio, ref_audio = left, right
    else:
        proc_audio, ref_audio = right, left

    ref_ch = 'R' if processed_ch == 'L' else 'L'

    print(f"\n--- Processed: {processed_ch} | Reference: {ref_ch} ---")

    # run VAD on both
    proc_segs = get_speech_segments(model, proc_audio)
    ref_segs = get_speech_segments(model, ref_audio)

    print(f"  {processed_ch} channel speech segments: {len(proc_segs)}")
    print(f"  {ref_ch} channel speech segments: {len(ref_segs)}")

    # classify
    classified = classify_segments(proc_segs, ref_segs)

    # compute stats
    isolated = [s for s in classified if s['status'] == 'ISOLATED']
    overlapped = [s for s in classified if s['status'] == 'OVERLAP']

    isolated_sec = sum(s['duration'] for s in isolated)
    overlap_sec = sum(s['duration'] for s in overlapped)
    total_speech = isolated_sec + overlap_sec

    usable_pct = (isolated_sec / total_speech * 100) if total_speech > 0 else 0
    rejected_pct = (overlap_sec / total_speech * 100) if total_speech > 0 else 0

    # print report
    print(f"\n  Total duration     : {total_duration:.2f}s")
    print(f"  Total speech       : {total_speech:.2f}s")
    print(f"  Isolated (usable)  : {isolated_sec:.2f}s ({usable_pct:.1f}%)")
    print(f"  Overlap (rejected) : {overlap_sec:.2f}s ({rejected_pct:.1f}%)")
    print(f"  Usable segments    : {len(isolated)}")
    print(f"  Rejected segments  : {len(overlapped)}")

    # segment details
    print(f"\n  {'#':<4} {'Start':>7} {'End':>7} {'Dur':>6} {'Status':<10}")
    print(f"  {'-'*40}")
    for i, seg in enumerate(classified, 1):
        marker = 'Y' if seg['status'] == 'ISOLATED' else 'X'
        print(f"  {i:<4} {seg['start']:>7.2f} {seg['end']:>7.2f} "
              f"{seg['duration']:>6.2f} {seg['status']:<10} [{marker}]")

    # feasibility
    if usable_pct >= 70:
        verdict = "HIGH - plenty of isolated speech"
    elif usable_pct >= 40:
        verdict = "MEDIUM - usable but noticeable overlap"
    else:
        verdict = "LOW - heavy overlap, may need extra filtering"

    print(f"\n  Feasibility: {verdict}")

    return {
        'processed_channel': processed_ch,
        'reference_channel': ref_ch,
        'total_duration': round(total_duration, 3),
        'total_speech_sec': round(total_speech, 3),
        'isolated_sec': round(isolated_sec, 3),
        'overlap_sec': round(overlap_sec, 3),
        'usable_pct': round(usable_pct, 2),
        'rejected_pct': round(rejected_pct, 2),
        'num_usable': len(isolated),
        'num_rejected': len(overlapped),
        'segments': classified,
        'feasibility': verdict
    }


# ---- Main ----

def main():
    # Hardcode your audio path and channel
    class Args:
        input = "/content/1.wav"  # <-- put your full path here
        channel = "both"
        output = "experiment_results.json"

    args = Args()

    # load model
    print("Loading Silero VAD model...")
    model = load_silero_vad()

    # load audio
    left, right, duration = load_stereo(args.input)

    # decide channels
    channels = ['L', 'R'] if args.channel == 'both' else [args.channel.upper()]

    all_results = []
    for ch in channels:
        result = analyze_channel(model, left, right, duration, processed_ch=ch)
        all_results.append(result)

    # save results
    with open(args.output, 'w') as f:
        json.dump(all_results, f, indent=2)
    print(f"\nResults saved to: {args.output}")


if __name__ == '__main__':
    main()

!pip install silero-vad torchaudio